const Filme = require('./server/models/filme')

Filme.forge({ nome: 'Harry Potter e a Pedra Filosofal', diretor: 'Chris Columbus' }).save()
Filme.forge({ nome: 'Harry Potter e a Câmara dos Segredos', diretor: 'Chris Columbus' }).save()
Filme.forge({ nome: 'Harry Potter e o Prisioneiro de Azkaban', diretor: 'Alfonso Cuarón' }).save()
Filme.forge({ nome: 'O Rei Leão', diretor: 'Jon Favreau' }).save()
Filme.forge({ nome: 'Procurando Nemo', diretor: 'Andrew Stanton' }).save()
Filme.forge({ nome: 'Procurando Dory', diretor: 'Andrew Stanton' }).save()
Filme.forge({ nome: 'Toy Story', diretor: 'John Lasseter' }).save()
Filme.forge({ nome: 'Toy Story 2', diretor: 'John Lasseter' }).save()
Filme.forge({ nome: 'Toy Story 3', diretor: 'Lee Unkrich' }).save()
Filme.forge({ nome: 'Toy Story 4', diretor: 'Josh Cooley' }).save()